#log相关配置
logging:
  path: C:/log/dingding
  level:
    root: INFO
    org.springframework.web: INFO

server:
  port: 8081

#跳转的网页地址
dingdingUrl: http://a2610377b5.zicp.vip/H5View/#/dingding/PlanOrderDetailPageDingDing

#钉钉配置
dingding:
  corpId: ding4ea5826e2e1e1c0fee0f45d8e4f7c288
  baseUrl: https://oapi.dingtalk.com
  appConfigs:
   - appKey: ding6fgb5hzzolxhe0ce
     appsecret: PHE5NeUNxqaZAyYHC6D9mYbSjvPsaXu2LPxdv5n9MLpwNBWDbuyz4CrzwgnE5KwB
     agentId: 844793405
   - appKey: 111
     appsecret: 222
     agentId: 333
  appidConfigs:
   - appId: dingoa7ntlpbq3z2nu523m
     appSecret: Af1zUlPoXVffwjsM6_PCcUiP35E9iMpTUeBp1oUwYBZ-nnz_JyzqYw0skJkqppKD
